import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Alex Moreira</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Pagina em manuntenção!</h1>

        <p className={styles.description}>
          Confira meus outros projetos no <a href="https://github.com/MoreiraAlex" target="_blank"  rel="noopener noreferrer">Github</a>
        </p>
      </main>

      <footer className={styles.footer}>
        <div>
          <a href="https://github.com/MoreiraAlex" target="_blank" rel="noopener noreferrer">
            Desenvolvido por Alex Moreira
          </a>
          <p className={styles.cnpj}>
            41.925.661 ALEX INOCENCIO MOREIRA - 41.925.661/0001-05
          </p>
        </div>
      </footer>
    </div>
  )
}
